version: '3.8'
services:
  backend:
    container_name: loja-backend
    build:
      context: ./backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
  db:
    container_name: loja-db
    image: mysql:8
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_db_loja:/var/lib/mysql
      - mysql_db_loja_config:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

volumes:
  mysql_db_loja:
  mysql_db_loja_config:
